### ISSUE TITLE
ng-audio shouldn't console.log

### ISSUE THREAD

**Issue by jakerenzella** [agroupp/ng-waveform#10]
The component runs `console.log('Audio Decoded.', decodedBuffer);` once the audio is processed (not an error).

I don't believe this should occur. Our app should not have the console logged to by components from libraries functioning as intended.

Thoughts? Thanks again for the great component 👍

**Comment by agroupp** [comment]
Of course, missed it.

**Comment by davecoffin** [comment]
This was my bad. 
https://github.com/agroupp/ng-audio/pull/15

**Comment by davecoffin** [comment]
Canceled that PR since I noticed @jakerenzella you addressed in your awesome PR.
