### ISSUE TITLE
Rename ng-audio repo to ng-waveform

### ISSUE THREAD

**Issue by jakerenzella** [agroupp/ng-waveform#16]
I apologise for being pedantic, however this component is more interesting than the name `ng-audio` lets on. I personally found myself confused at the repository name when I was trying to find the repo.

I propose renaming the repository to `ng-waveform` to align it with the npm and component name.

Thoughts?

**Comment by davecoffin** [comment]
Totally agree with this.
This project is so good and could use some more standardization, so I totally support this idea.

**Comment by agroupp** [comment]
This repo is renamed to `ng-waveform`. It will be created new repo `ng-audio` with more functionality.
