### ISSUE TITLE
Playback after regionEnd (or no region at all) results in progress not stopping

### ISSUE THREAD

**Issue by jakerenzella** [agroupp/ng-waveform#9]
Hey all,

Great work on this.

It seems that playing with regions disabled, or just seeking past the regionEnd and playing audio results in progress not stopping, and the rectangle will continue to grow wider. This is occurring in your demo:

![Screen Shot 2020-09-24 at 11 56 00 pm](https://user-images.githubusercontent.com/5138218/94154741-8e6ef100-fec1-11ea-92d6-e822682bd7db.png)

See progress > 100%.

I would like to fix this myself but am working to a tight deadline at the moment on my projects, and hopefully, you can get to this sooner than I 👍

**Comment by agroupp** [comment]
Thank you, I'll check it.

**Comment by jakerenzella** [comment]
Thanks, @agroupp.

This is my current workaround, for anyone else visiting.

```
this.waveform.timeUpdate.subscribe(() => {
      if (this.waveform.progress >= 100) {
        this.waveform.pause();
      }
    });
```

**Comment by agroupp** [comment]
Yes, you right. I missed it.

**Comment by jakerenzella** [comment]
A potential solution in #12
